import Head from "next/head";
import Header from "../Component/Header";
import Nav from "../Component/Nav";
import Results from "../Component/Results";
import api from "../Services/api";

export default function Home({ movies, genres }) {
  if (!genres && !movies) {
    return <p>Loading...</p>;
  }
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://assetshuluimcom-a.akamaihd.net/h3o/facebook_share_thumb_default_hulu.jpg"
        />
      </Head>
      <Header />
      <Nav genres={genres} />
      <Results results={movies} />
    </div>
  );
}

export async function getStaticProps(context) {
  let genres = null;
  let movies = null;
  let genre = context.params.genre;
  try {
    genres = await api.getGenres();
  } catch {}

  let currentGenre = genres.filter((g) => g.name == genre)[0];

  try {
    movies = await api.getMovies(currentGenre.id);
  } catch {}

  return {
    props: { movies, genres },
    revalidate: 60 * 60 * 24,
  };
}

export async function getStaticPaths() {
  let genres = null;

  try {
    genres = await api.getGenres();
  } catch {}

  if (!genres) return { paths: [], fallback: true };

  const paths = genres.map((genre) => ({
    params: { genre: genre.name },
  }));

  return { paths, fallback: "blocking" };
}
