import Head from "next/head";
import Header from "../Component/Header";
import Nav from "../Component/Nav";
import Results from "../Component/Results";
import api from "../Services/api";

export default function Home({ movies, genres }) {
  if (!genres && !movies) {
    return <p>Loading...</p>;
  }
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://assetshuluimcom-a.akamaihd.net/h3o/facebook_share_thumb_default_hulu.jpg"
        />
      </Head>
      <Header />
      <Nav genres={genres} />
      <Results results={movies} />
    </div>
  );
}

export async function getStaticProps() {
  let movies = null;
  let genres = null;
  try {
    movies = await api.getMovies();
    genres = await api.getGenres();
  } catch {}

  return {
    props: { movies, genres },
    revalidate: 60 * 60 * 24,
  };
}
