import Head from "next/head";
import Hearder from "../Component/Hearder";
import Nav from "../Component/Nav";
import Results from "../Component/Results";
import requests from "../requests";
import axios from "axios";
export default function Home({ movie }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://assetshuluimcom-a.akamaihd.net/h3o/facebook_share_thumb_default_hulu.jpg"
        />
      </Head>
      <Hearder />
      <Nav />
      <Results results={movie} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const { genre } = context.query;
  const request = await axios(
    `https://api.themoviedb.org/3${
      requests[genre || "fetchTranding"].url || requests.fetchTranding.url
    }`
  );
  const movie = request.data.results;
  return {
    props: { movie },
  };
}
