import Head from "next/head";
import Header from "../Component/Header";
import Nav from "../Component/Nav";
import Results from "../Component/Results";

export default function Home({ movies, genres }) {
  if (!genres && !movies) {
    return <p>Loading...</p>;
  }
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://assetshuluimcom-a.akamaihd.net/h3o/facebook_share_thumb_default_hulu.jpg"
        />
      </Head>
      <Header />
      <Nav genres={genres} />
      <Results results={movies} />
    </div>
  );
}

export async function getStaticProps() {
  let movies = null;
  let genres = null;
  try {
    movies = await getMovies();
    genres = await getGenres();
  } catch {}

  return {
    props: { movies, genres },
    revalidate: 60 * 60 * 24,
  };
}

async function getGenres() {
  const res = await fetch(
    "https://api.themoviedb.org/3/genre/movie/list?api_key=32617012bea77a3729ee98ea76ff44a2"
  );
  const data = await res.json();

  return data.genres;
}

async function getMovies(id = null) {
  const url = `https://api.themoviedb.org/3/movie/popular?api_key=32617012bea77a3729ee98ea76ff44a2&language=en-US&page=1`;

  if (id) {
    url += `&with_genres=${id}`;
  }

  const res = await fetch(url);

  const data = await res.json();

  return data.results;
}
